using UnityEngine;
using UnityEngine.UI;

namespace MyDefence
{
    /// <summary>
    /// Enemy ë¥¼ ê´€ë¦¬í•˜ëŠ” í´ë˜ìŠ¤
    /// </summary>
    public class Enemy_N : MonoBehaviour, IDamageable
    {
        #region Variables
        [SerializeField]
        private Node nextNode;

        //ì´ë™ ëª©í‘œ ìœ„ì¹˜ë¥¼ ê°€ì§€ê³  ìˆëŠ” ì˜¤ë¸Œì íŠ¸
        private Transform target;

        //ì´ë™ ì†ë„
        [SerializeField]
        private float speed = 10f;

        //ì´ë™ì†ë„ ì´ˆê¸°í™”
        [SerializeField]
        private float startSpeed = 4f;

        //íšŒì „ ì†ë„
        public float rotationSpeed = 5f;

        //ì´ë™ ì›¨ì´í¬ì¸íŠ¸ ì¸ë±ìŠ¤
        int wayPointIndex;

        //ì²´ë ¥
        private float health;

        [SerializeField]
        private float startHealth = 100f;    //ì²´ë ¥ ì´ˆê¸°ê°’

        //ì£½ìŒ ì²´í¬
        private bool isDeath = false;

        //ì£½ìŒ íš¨ê³¼
        public GameObject deathEffectPrefab;

        //ì£½ìŒ ë³´ìƒ
        [SerializeField]
        private int rewardMoney = 50;

        //UI
        public Image hpBarImage;
        #endregion


        #region Unity Event Method
        // Start is called once before the first execution of Update after the MonoBehaviour is created
        void Start()
        {
            //ì´ˆê¸°í™”
            health = startHealth;
            speed = startSpeed;
            wayPointIndex = 0;

            //ì´ë™ ëª©í‘œì§€ì  0ë²ˆì—ì„œ ì„¤ì •
            //target = WayPoints.points[wayPointIndex];
        }

        // Update is called once per frame
        void Update()
        {
            if (target == null) return;

            // íƒ€ê²Ÿ ë°©í–¥ ê³„ì‚°
            Vector3 dir = target.position - this.transform.position;

            if (dir != Vector3.zero)
            {
                Quaternion targetRot = Quaternion.LookRotation(dir);
                transform.rotation = Quaternion.Slerp(transform.rotation, targetRot, rotationSpeed * Time.deltaTime);
            }

            //íƒ€ê²Ÿì„ í–¥í•´ ì´ë™
            transform.Translate(Vector3.forward * speed * Time.deltaTime);

            // ğŸ”¹ ë„ì°© íŒì •
            //íƒ€ê²Ÿê³¼ Eenmyì™€ ê±°ë¦¬ë¥¼ êµ¬í•´ì„œ ì¼ì •ê±°ë¦¬ì•ˆì— ë“¤ì–´ì˜¤ë©´ ë„ì°©ì´ë¼ê³  íŒì •í•œë‹¤
            float distance = Vector3.Distance(target.position, this.transform.position);
            if (distance <= 0.1f)
            {
                SetNextTarget();
            }
            //ì´ë™ì†ë„ ì´ˆê¸° ì†ë„ë¡œ ë³µì›
            speed = startSpeed;
        }
        #endregion

        #region Custom Method
        //ë‹¤ìŒ Node ì„¤ì •
        public void SetNextNode(Node next)
        {
            // NextNode: ë‚˜ ë‹¤ìŒì— ì´ë™í•  ë…¸ë“œ(next)ë¥¼ ê°€ì§€ê³  ìˆë‹¤.
            nextNode = next;
            target = nextNode.transform;
        }

        //ë‹¤ìŒ íƒ€ê²Ÿ ì„¤ì •
        void SetNextTarget()
        {
            //ë‹¤ìŒì— ì´ë™í•  ë…¸ë“œ ê°€ì ¸ì˜¤ê¸°
            Node next = nextNode.GetNextNode();

            //ì¢…ì  ì²´í¬
            if (next == null)
            {
                Arrive();
                return;    
            }

            SetNextNode(next);
        }

        //ì¢…ì  ë„ì°©
        private void Arrive()
        {
            Debug.Log("ë„ì°©");
            //ìƒëª… ì‚¬ìš©
            PlayerStats.UseLives(1);

            //ì‚´ì•„ ìˆëŠ” ì ì˜ ìˆ˜ë¥¼ ì¤„ì¸ë‹¤
            WaveSpawnManager.enemyAlive--;

            //Enemy í‚¬
            Destroy(this.gameObject);
        }

        //ë§¤ê°œë³€ìˆ˜ë¡œ ë“¤ì–´ì˜¨ ë§Œí¼ ë°ë¯¸ì§€ë¥¼ ì…ëŠ”ë‹¤
        public void TakeDamage(float damage)
        {
            health -= damage;
            //Debug.Log($"Enemy Health: {health}");

            //UI
            hpBarImage.fillAmount = health / startHealth;

            //ì£½ìŒ ì²´í¬
            if (health <= 0 && isDeath == false)
            {
                health = 0;
                Die();
            }
        }

        //ì£½ìŒ ì²˜ë¦¬
        private void Die()
        {
            //ì£½ìŒ ì²´í¬
            isDeath = true;

            //ì£½ìŒ ì²˜ë¦¬...
            //effct íš¨ê³¼ (vfx, sfx)
            GameObject effectGo = Instantiate(deathEffectPrefab, this.transform.position, Quaternion.identity);
            Destroy(effectGo, 2f);

            //ì‚´ì•„ ìˆëŠ” ì ì˜ ìˆ˜ë¥¼ ì¤„ì¸ë‹¤
            WaveSpawnManager.enemyAlive--;

            //ë³´ìƒ ì²˜ë¦¬(ê³¨ë“œ, ê²½í—˜ì¹˜, ì•„ì´í…œ..)
            PlayerStats.AddMoney(rewardMoney);

            //Enemy Kill
            Destroy(this.gameObject);
        }

        //ì´ë™ì†ë„ ëŠë¦¬ê²Œ í•˜ê¸°
        public void Slow(float rate)    //40%
        {
            speed = startSpeed * (1 - rate);       //4 * (1 - 0.4) = 2.4
        }
        #endregion
    }
}